### ISSUE TITLE
NCRF++ not NCRFpp++

### ISSUE THREAD

**Issue by jiesutd** [aghie/tree2labels#1]
Hi @aghie , really a nice work. 

A small problem is that the framework you used in the paper is named as "NCRF++" rather than the "NCRFPP++". The github repo folder is NCRFpp because the "pp" means plusplus (++).

**Comment by aghie** [comment]
Thanks @jiesutd for pointing out the typo (and developing NCRF++, it made things much easier). I plan to update the paper in arxiv in the near future to include some additional results, so I made a note of this and change it too.

**Comment by jiesutd** [comment]
Thank you very much! Glad to know our work helps : )
