### ISSUE TITLE
Lower F score when I execute and evaluate the pre-trained models

### ISSUE THREAD

**Issue by mjj1094** [aghie/tree2labels#4]
data: PTB

Transforming the data:
python dataset.py --train ptb/02-21.10way.clean --dev ptb/22.10way.clean --test ptb/23.10way.clean --output $PATH_OUTPUT_DIR --treebank PTB --encode_unaries --os --abs_top 3 --abs_neg_gap 2 
multitask(3 files, one is as following):
python encoding2multitask.py --input ./data/ptb/PTB-train.seq_lu --output ./data/ptb/PTB-train.seq_lu.multitask --status encode

evaluating:
taskset --cpu-list 1 python run_ncrfpp.py --test ./data/ptb/tree2labels-2019/PTB-test.seq_lu.multitask  --gold ./data/ptb/ptb/23.auto.clean --model ./models/ptb/ptb.multitask.3R.-2.pre_lev --status test --gpu True --output ./data/ptb/output/ptb.multitask.3R.-2.pre_lev.test  --evalb ./EVALB/evalb --ncrfpp ./NCRFpp --multitask

Looking for your reply sincerely,thanks!

**Comment by aghie** [comment]
Hi, 

Can it be possible that you are using different postags than the ones specified in the paper? Also, how big is this difference?

**Comment by mjj1094** [comment]
the PTB data I used is just the version specified in the paper, and the results on test are:
Number of sentence        =   2416
Bracketing Recall         =  85.18
Bracketing Precision      =  91.37
Bracketing FMeasure       =  88.17

**Comment by aghie** [comment]
Just made a fresh install and I am getting (using scripts/run_ncrfpp_multitask.sh):

Number of sentence        =   2416
Number of Error sentence  =      0
Number of Skip  sentence  =      0
Number of Valid sentence  =   2416
Bracketing Recall         =  89.83
Bracketing Precision      =  91.37
Bracketing FMeasure       =  90.59

If you like, you can send me an email with your ptb test file to see if there is any mismatch (e.g. different predicted part-of-speech tags).

**Comment by mjj1094** [comment]
thank you very much,I will send you the test file.

**Comment by mjj1094** [comment]
I am afraid wrote the wrong email address, could you write it here?

**Comment by aghie** [comment]
Got the email and replied.

**Comment by mjj1094** [comment]
Thank you !
