### ISSUE TITLE
extensibility of codes

### ISSUE THREAD

**Issue by hour** [aghie/tree2labels#5]
Dear author,

Tree2labels technique is interesting to me and I appreciate the sharing of codes.
But the tree transformation script (dataset.py) is somehow difficult to be reused.

I wish to see the scripts which allow to transform from tree to label and back to tree.
E.g. 
`tree2label.py < input_trees > output_labels `
and 
`label2tree.py < input_labels > output_trees`

Also, I am curious if the transformation doesn't drop syntax tree information.
E.g. If I do
`cat tree.original | tree2label.py | label2tree.py > tree.recovered`
Will " tree.recovered" equal "tree.original"?

Thank in advance for considering my comment.

Best,

**Comment by hour** [comment]
I closed it because it is just a suggestion.

**Comment by aghie** [comment]
Nice point. I will consider it.

The linearization is not lossy. For a theoretical demonstration you can check the details in the paper (Constituent Parsing as Sequence Labeling).
